Weather
AleksanderLeontiev/weather pull request #2
Opened 2021-01-31 14:46 UTC by AleksanderLeontiev

2021-02-01 00:39 UTC, AntiHero requested changes

2021-02-01 00:39 UTC, AntiHero commented on babel.config.js
> +module.exports = {
кажется что этот файл форматирование prettier'ом не проходил?

2021-02-01 00:39 UTC, AntiHero commented on index.html
> +		<meta charset="UTF-8" />
а почему и зачем такие  большие отступы?

2021-02-01 00:39 UTC, AntiHero commented on index.html
> +		<div class="weather__city"></div>
если пишешь название элемента, то должно присутствовать и название блока (родительского элемента), но его у тебя нет, этот элемент и есть "родитель",  поэтом класс можно переименовать как `weather-city`

2021-02-01 00:39 UTC, AntiHero commented on index.html
> +			<ol id="cities" style="cursor: pointer"></ol>
почему тут решил использовать id?

2021-02-01 00:39 UTC, AntiHero commented on index.html
> +		<img id="map" />
и здесь?

2021-02-01 00:39 UTC, AntiHero commented on package.json
> +    "@babel/polyfill": "^7.12.1",
> As of Babel 7.4.0, this package has been deprecated in favor of directly including core-js/stable

https://babeljs.io/docs/en/babel-polyfill/
теперь вопрос, нужен ли он тебе? и второй вопрос:  почему это всё в dependencies?

2021-02-01 00:39 UTC, AntiHero commented on package.json
> +  "jest": {
насколько я видел jest.config у тебя есть) так какой из ты используешь?

2021-02-01 00:39 UTC, AntiHero commented on src/api.js
> +const appId = `2a65fd6cf7e06ab6144595db8eef6f98`;
как мы такие константы называем? в СAMEL_CASE

2021-02-01 00:39 UTC, AntiHero commented on src/api.test.js
> +// jest.mock("./api");
комменты не забывай удалять, пробежись по всем файлам пожалуйста

2021-02-01 00:39 UTC, AntiHero commented on src/app.js
> +	// .catch(exp => console.error(exp));//если ошибка вывожу в консоль
почему убрал? можешь кстати придумать свой способ отлавливания ошибок, например возвращать какой-то объект ошибки

2021-02-01 00:39 UTC, AntiHero commented on src/app.js
> +	const citiesElement = document.getElementById("cities"); // див ол
.querySelector(название класса вместо id)

2021-02-01 00:39 UTC, AntiHero commented on babel.config.js
> +				targets: { node: "current" },
точно node?)посмотри https://babeljs.io/docs/en/babel-preset-env может найдёшь для себя что-нибудь полезное

2021-02-01 00:39 UTC, AntiHero commented on src/app_test.test.js
> +import * as module from "./api";
apiModule вместо module, например, module у тебя может быть любой твой .js файл, а здесь ты явно задаёшь имя, которое не  спутаешь

2021-02-01 00:39 UTC, AntiHero commented on src/app_test.test.js
> +		expect(module.getWeather).toBeCalled();
а зачем придумывать `.resolve({ city: "Moscow" })` если ты это не проверяшь?

2021-02-01 00:39 UTC, AntiHero commented on src/app_test.test.js
> +function timeout(ms) {
я бы вынес её в отдельный файлик, например utils.js

2021-02-01 00:39 UTC, AntiHero commented on src/storage.test.js
> +		global.localStorage.__proto__.setItem = jest.fn();
здесь  ты перезаписываешь setItem, так делать не стоит, если используеешь spyOn,  то егго можно  использовать в   связке с mockImplementation

2021-02-01 00:39 UTC, AntiHero commented on webpack.config.js
> +const HtmlWebpackPlugin = require("html-webpack-plugin");
скажу тебе  по секрету что cюда прекрасно можно поместить настройки для babel) https://webpack.js.org/loaders/babel-loader/

2021-02-01 00:39 UTC, AntiHero commented on src/storage.test.js
> +import "regenerator-runtime/runtime";
уверен что тебе нужны импорты regenerator-runtime? и в других файлах тоже

2021-02-01 00:39 UTC, AntiHero commented on src/api.test.js
> +import { getSrcMap, getWeather } from "./api";
а ты используешь эти функции в тесте? зачем тогда импортируешь?

2021-02-01 00:39 UTC, AntiHero commented on .eslintrc.js
> +		"no-unused-vars": "off",
удобные правила, верно?) но если ты так много отключаешь, теряется смысл использования eslint, подумай как ты можешь свести к минимуму  отключение правил eslint

2021-02-01 07:33 UTC, AleksanderLeontiev commented on src/storage.test.js
> +		global.localStorage.__proto__.setItem = jest.fn();
jest.spyOn(global.localStorage.__proto__, "setItem").mockImplementation(global.localStorage.__proto__.setItem);
наверное так

2021-02-01 08:29 UTC, AleksanderLeontiev commented on index.html
> +			<ol id="cities" style="cursor: pointer"></ol>
id использовал потому что выдает ошибку на HTML

2021-02-01 09:01 UTC, AleksanderLeontiev commented on src/storage.test.js
> +		global.localStorage.__proto__.setItem = jest.fn();
jest.fn(global.localStorage.__proto__.setItem); нет даже так

2021-02-01 12:53 UTC, AntiHero commented on index.html
> +			<ol id="cities" style="cursor: pointer"></ol>
ошибка на HTML? поясни пожалуйста

2021-02-01 12:56 UTC, AntiHero commented on src/storage.test.js
> +		global.localStorage.__proto__.setItem = jest.fn();
jest.fn(global.localStorage.__proto__.setItem); это что такое? безымянная имплементация?
jest.spyOn(global.localStorage.proto, "setItem").mockImplementation(global.localStorage.proto.setItem);  а вот тут ты 'следишь' за методом setItem, и мокаешь такую же имплементацию, какая у этого метода и была?
и почитай пожалуйс (или посмотри) про **proto**
https://www.youtube.com/watch?v=b55hiUlhAzI

2021-02-01 14:53 UTC, AleksanderLeontiev commented on babel.config.js
> +				targets: { node: "current" },
{
  "targets": {
    "chrome": "58",
    "ie": "11"
  }
}
при таком варианте тесты падают

2021-02-01 15:10 UTC, AntiHero commented on babel.config.js
> +				targets: { node: "current" },
а при таком?
`"targets": "> 0.25%, not dead"`

2021-02-01 15:12 UTC, AleksanderLeontiev commented on index.html
> +			<ol id="cities" style="cursor: pointer"></ol>
● renders the list › list li

    TypeError: Cannot read property 'appendChild' of null

      29 |      const li = document.createElement("li");
      30 |      li.innerText = city;
    > 31 |      citiesElement.appendChild(li);
         |                    ^
      32 | }

2021-02-01 15:16 UTC, AleksanderLeontiev commented on index.html
> +			<ol id="cities" style="cursor: pointer"></ol>
Александр прошу прощения пропустил точку querySelector(".cities");   ))

2021-02-01 15:21 UTC, AleksanderLeontiev commented on babel.config.js
> +				targets: { node: "current" },
при таком тоже

2021-02-01 16:02 UTC, AntiHero commented on babel.config.js
> +				targets: { node: "current" },
прикрепи  пожалуйста скрин ошибки

2021-02-01 16:27 UTC, AntiHero commented on babel.config.js
> +				targets: { node: "current" },
https://babeljs.io/docs/en/babel-plugin-transform-regenerator
устанавливаешь плагин, добавляешь плагин в babel.config

2021-02-03 13:53 UTC, AntiHero requested changes

2021-02-03 13:53 UTC, AntiHero commented on .github/workflows/codecov-test-suites.yml
> +jobs:
name: Run Test Suites

on: [push]

забыл добавить, поэтому у тебя чек  и не запускается

2021-02-07 12:24 UTC, AntiHero commented on src/app.js
> +	getCity().then((obj) => {
единственный момент, почему  такие  огромные  отступы?))

2021-02-07 12:28 UTC, AntiHero requested changes

2021-02-07 12:28 UTC, AntiHero commented on package.json
> +    "@types/jest": "^26.0.16",
друг, ну сколько раз  уже обсуждали,  где это всё должно быть? тесты и core-js где у тебя используются? на какой стадии? значит где это  это  всё должно  быть, в dependencies или всё  же devdependencies?

2021-02-09 11:17 UTC, AntiHero commented on package.json
> +    "core-js": "^3.8.1"
а почему  это  в dev не перенёс?

2021-02-09 11:17 UTC, AntiHero commented on src/app.js
> +	while (citiesElement.firstChild) {
лучше `while( сitiesElement.hasChildElements() )`

2021-02-09 11:17 UTC, AntiHero commented on src/app_test.test.js
> +		const cities = "ufa";
только наверное city а не cities

2021-02-09 11:17 UTC, AntiHero commented on src/api.js
> +const geo = "https://get.geojs.io/v1/ip/geo.json";
GEO

2021-02-09 11:17 UTC, AntiHero commented on src/app.js
> +	const { value } = input;
а зачем  это  делать?  использовать деструктуризацию  для одной  проверки? можно было просто input.value  проверить и всё

2021-02-10 07:18 UTC, merged